Repository Hydractify/kanna_kobayashi, pull requests merged in 2019-01, with the labels that each got.

#26 Remove currency system
  src/commands/common/commandUsage.ts
  src/commands/common/help.ts
  src/commands/common/info.ts
  src/commands/common/ping.ts
  src/commands/common/stats.ts
  src/commands/fun/catch.ts
  src/commands/fun/daily.ts
  src/commands/fun/gamble.ts
  src/commands/quiz/quizduration.ts
  src/commands/quiz/quizname.ts
  src/commands/quiz/quizphoto.ts
  src/commands/quiz/quizpremade.ts
  src/commands/quiz/quizstart.ts
  src/commands/settings/commandstatus.ts
  src/commands/settings/disablecommand.ts
  src/commands/settings/enablecommand.ts
  src/commands/settings/farewellmessage.ts
  src/commands/settings/levelup.ts
  src/commands/settings/notif.ts
  src/commands/settings/prefix.ts
  src/commands/settings/removeprefix.ts
  src/commands/settings/selfroles.ts
  src/commands/settings/welcomemessage.ts
  src/commands/unique/blacklist.ts
  src/commands/unique/eval.ts
  src/commands/unique/exec.ts
  src/commands/unique/reload.ts
  src/commands/unique/restart.ts
  src/commands/unique/set.ts
  src/commands/unique/setgame.ts
  src/commands/unique/whitelist.ts
  src/commands/user/addreputation.ts
  src/commands/user/balance.ts
  src/commands/user/block.ts
  src/commands/user/blocklist.ts
  src/commands/user/breakup.ts
  src/commands/user/deletereputation.ts
  src/commands/user/donate.ts
  src/commands/user/item.ts
  src/commands/user/leaderboard.ts
  src/commands/user/market.ts
  src/commands/user/profile.ts
  src/commands/user/propose.ts
  src/commands/user/removereputation.ts
  src/commands/user/showreputation.ts
  src/commands/user/unblock.ts
  src/index.ts
  src/models/Badge.ts
  src/models/Item.ts
  src/models/User.ts
  src/scripts/buildItems.ts
  src/scripts/itemList.ts
  src/structures/Command.ts
  src/types/Badges.ts
  src/types/ICommandInfo.ts
  src/types/IItemStructure.ts
  src/types/ILeaderBoardUser.ts
  src/types/ItemRarities.ts
  src/types/ItemTypes.ts
  src/types/Items.ts
Labels: enhancement

#30 fix: actually post to bot lists
  src/extensions/ShardClientUtil.ts
  src/util/botlists.ts
Labels: fix

#31 fix(api): always reject with an instanceof Error if fetching failed
  src/structures/Api.ts
Labels: fix

#29 refactor(reload): allow multiple commands, more packed output
  src/commands/unique/reload.ts
  src/extensions/ShardClientUtil.ts
Labels: enhancement, refactor
