Repository Hydractify/kanna_kobayashi, pull requests merged in 2019-11, with the labels that each got.

#68 chore(README): remove trello badge
  README.md
Labels: documentation

#69 docs(commands): fix spelling mistakes
  src/commands/common/help.ts
  src/commands/info/avatar.ts
  src/commands/info/guild.ts
  src/commands/info/osuuser.ts
  src/commands/meme/doit.ts
  src/commands/user/blocklist.ts
Labels: enhancement, fix

#70 fix(ChooseCommand): only split on expected delimiters, filter empty results
  src/commands/fun/choose.ts
Labels: fix

#71 fix(LookupCommand): show the guild of the invite, if present, disallow gdm invites
  src/commands/info/guild.ts
  src/commands/info/lookup.ts
Labels: fix

#72 fix(InteractiveCommands): call parent parseArgs to take care of blocks
  src/commands/interactive/blush.ts
  src/commands/interactive/cry.ts
  src/commands/interactive/dance.ts
Labels: fix

#73 fix(LeaderboardCommand): add level as alias to exp
  src/commands/user/leaderboard.ts
Labels: fix
