Repository Hydractify/kanna_kobayashi, pull requests merged in 2019-05, with the labels that each got.

#38 fix(BlockListCommand): inform the user when sending a dm failed
  src/commands/user/blocklist.ts
  src/extensions/Extension.ts
Labels: fix

#40 feat(ProfileCommand): add relationship anniversary
  src/commands/user/profile.ts
Labels: feature

#41 fix(SetGameCommand): do not send url if not streaming
  src/commands/unique/setgame.ts
Labels: fix

#42 fix(ProfileCommand): add utc offset to the anniversary date
  src/commands/user/leaderboard.ts
  src/commands/user/profile.ts
Labels: fix

#43 feat(Prometheus): add counters and gauges
  package.json
  src/Shard.ts
  src/index.ts
  src/structures/Client.ts
  src/structures/CommandHandler.ts
  src/structures/Prometheus.ts
  yarn.lock
Labels: feature

#44 Fix/prometheus/cpu usage
  src/structures/Prometheus.ts
Labels: fix

#45 feat(CommandHandler): allow spaces after the prefix (or the lack thereof)
  src/structures/CommandHandler.ts
Labels: enhancement, feature

#46 refactor: cut down webhook frequency by logging less events
  src/Shard.ts
  src/index.ts
  src/structures/Client.ts
  src/structures/CommandHandler.ts
Labels: refactor

#47 GitHub changes
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/ISSUE_TEMPLATE/suggest-an-improvement.md
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
  README.md
  data.example.json
Labels: enhancement
