Repository Hydractify/kanna_kobayashi, pull requests merged in 2020-04, with the labels that each got.

#84 chore: update discord.js and its dependencies
  .travis.yml
  package.json
  src/commands/common/stats.ts
  src/commands/info/emoji.ts
  src/commands/info/guild.ts
  src/commands/info/lookup.ts
  src/commands/info/modlist.ts
  src/commands/info/role.ts
  src/commands/info/user.ts
  src/commands/quiz/quizstart.ts
  src/commands/settings/notif.ts
  src/commands/settings/selfroles.ts
  src/commands/user/blocklist.ts
  src/commands/user/leaderboard.ts
  src/commands/user/profile.ts
  src/extensions/Extension.ts
  src/extensions/GuildMemberStore.ts
  src/index.ts
  src/models/User.ts
  src/structures/Client.ts
  src/structures/CommandHandler.ts
  src/structures/MessageEmbed.ts
  src/structures/Resolver.ts
  src/types/IFetchableManager.ts
  src/types/IFetchableStore.ts
  src/util/Util.ts
  yarn.lock
Labels: enhancement, refactor

#85 fix: delete unused messages from cache, not from Discord
  src/structures/Client.ts
  src/structures/CommandHandler.ts
Labels: fix

#86 fix: use Structures from discord.js in order to properly extend user and guild
  src/extensions/Extension.ts
  src/extensions/Guild.ts
  src/extensions/User.ts
Labels: fix

#87 feat(SelfRolesCommand): use role mentions instead of role names
  src/commands/settings/selfroles.ts
Labels: enhancement

#88 debug(Client): add more webhook events, make shard id more visible
  src/index.ts
  src/structures/Client.ts
Labels: enhancement, fix

#90 chore: bump to v4.6.2 + .github/README changes
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  package.json
Labels: documentation

#93 feat(SetGameCommand): initially set and regularly refresh an activity
  src/commands/unique/setgame.ts
  src/structures/Client.ts
Labels: enhancement

#91 chore: update pg to fix node v14 compat
  package.json
  yarn.lock
Labels: bug

#92 debug(Client): use correct capture group for reason match on close
  src/structures/Client.ts
Labels: bug

#94 feat(StatsCommand): mark the current shard with an asterisk
  src/commands/common/stats.ts
  src/types/IShardData.ts
Labels: enhancement

#95 fix(SetGameCommand): actually publish the activity and only set it on the last shard
  src/commands/unique/setgame.ts
  src/structures/Client.ts
Labels: bug

#98 fix(MessageEmbed): override toJSON method to truncate embeds that are too long
  src/structures/MessageEmbed.ts
Labels: bug

#97 fix(RestartCommand): use process messages instead of broadcast eval
  src/Shard.ts
  src/commands/unique/restart.ts
  src/types/IPCMessageType.ts
Labels: bug

#96 fix: use typed broadcastEval over fetchClientValues
  src/commands/unique/setgame.ts
  src/structures/Client.ts
  src/util/botlists.ts
Labels: bug
