Repository Hydractify/kanna_kobayashi, pull requests merged in 2020-05, with the labels that each got.

#99 fix(StatsCommand): properly pad the current shard marker
  src/commands/common/stats.ts
Labels: fix

#101 fix: wrap parameter in parentheses to fix broadcast eval
  src/commands/unique/setgame.ts
  src/structures/Client.ts
  src/util/botlists.ts
Labels: fix

#100 fix: enable REACTION partial to reenable messageReactionAdd
  src/index.ts
  src/structures/Client.ts
Labels: fix

#102 refactor(logging): set process tag internally
  src/Shard.ts
  src/decorators/LoggerDecorator.ts
  src/extensions/ShardClientUtil.ts
  src/index.ts
  src/scripts/buildItems.ts
  src/structures/Client.ts
  src/structures/CommandHandler.ts
  src/structures/Logger.ts
  src/structures/PostgreSQL.ts
  src/structures/Prometheus.ts
  src/structures/WebhookLogger.ts
  src/util/botlists.ts
Labels: refactor

#104 fix(CryCommand): correctly make the trusted user bold when triggered
  src/commands/interactive/cry.ts
Labels: fix, spelling
